export const FETCH_ROLE_DATA = "FETCH_ROLE_DATA";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAIL = "FETCH_ROLE_FAIL";

export const ADD_ROLE_DATA = "ADD_ROLE_DATA";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAIL = "ADD_ROLE_FAIL";

export const DELETE_ROLE_DATA = "DELETE_ROLE_DATA";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";

export const EDIT_ROLE_DATA = "EDIT_ROLE_DATA";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const EDIT_ROLE_FAIL = "EDIT_ROLE_FAIL";

export const ROLE_MAP_REQUEST = "ROLE_MAP_REQUEST";
export const ROLE_MAP_SUCCESS = "ROLE_MAP_SUCCESS";
export const ROLE_MAP_FAIL = "ROLE_MAP_FAIL";

export const ROLE_MAP_WITH_USER_REQUEST = "ROLE_MAP_WITH_USER_REQUEST";
export const ROLE_MAP_WITH_USER_SUCCESS = "ROLE_MAP_WITH_USER_SUCCESS";
export const ROLE_MAP_WITH_USER_FAIL = "ROLE_MAP_WITH_USER_FAIL";
