export const FETCH_SCREEN_DATA = "FETCH_SCREEN_DATA";
export const FETCH_SCREEN_SUCCESS = "FETCH_SCREEN_SUCCESS";
export const FETCH_SCREEN_FAIL = "FETCH_SCREEN_FAIL";

export const ADD_NEW_SCREEN = "ADD_NEW_SCREEN";
export const SCREEN_ADD_SUCCESS = "SCREEN_ADD_SUCCESS";
export const SCREEN_ADD_FAIL = "SCREEN_ADD_SUCCESS";

export const UPDATE_SCREEN_REQUEST = "UPDATE_SCREEN_REQUEST";
export const UPDATE_SCREEN_SUCCESS = "UPDATE_SCREEN_SUCCESS";
export const UPDATE_SCREEN_FAIL = "UPDATE_SCREEN_SUCCESS";

export const DELETE_SCREEN_REQUEST = "DELETE_SCREEN_REQUEST";
export const DELETE_SCREEN_SUCCESS = "DELETE_SCREEN_SUCCESS";
export const DELETE_SCREEN_FAIL = "DELETE_SCREEN_SUCCESS";

export const EDIT_SCREEN_REQUEST = "EDIT_SCREEN_REQUEST";
export const EDIT_SCREEN_SUCCESS = "EDIT_SCREEN_SUCCESS";
export const EDIT_SCREEN_FAIL = "EDIT_SCREEN_SUCCESS";
